- name: install Nginx
  hosts: WEB
  become: true
  tasks:
- name: install nginx
      ansible.builtin.yum:
        name: httpd
        state: latest

- name: start nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enable: yes

- name: install Nginx
  hosts: WEB
  become: true
  roles:
    - sample

